# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"

  # Install the package, so that Sphinx can generate autodocs.
  # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
  jobs:
    post_create_environment:
      # Install uv
      # https://github.com/astral-sh/uv/issues/10074#issuecomment-2593075059
      - pip install uv
    post_install:
      # Virtualenv path needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group ci

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
