# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CI

on:
  push: ~

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Note: Use quotes to avoid float cast - especially important if the
          # version number ends with 0!
          # - "3.14" not released yet
          - "3.13"
          - "3.12"

    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group ci
      - name: Run tests
        run: uv run pytest

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --group ci
      - name: Type checking
        run: uv run mypy src test

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --group ci
      - name: Check docs build
        run: |
          cd docs
          mkdir -p _static
          uv run make html
